version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: maple-mongo
    restart: unless-stopped
    ports:
      - '27050:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123

  maple-auth:
    build:
      context: .
      dockerfile: apps/auth/dockerfile
    container_name: maple-auth
    restart: unless-stopped
    ports:
      - '5562:5562'
    depends_on:
      - mongo
    environment:
      NODE_ENV: prod
      SERVER_PORT: 5562
      JWT_SECRET: honeyjam
      JWT_EXPIRES_IN: 1h
      JWT_REFRESH_EXPIRES_IN: 7d
      MONGO_URI: mongodb://admin:admin123@mongo:27017/?authSource=admin
      MONGO_DB_NAME: maple
