version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: maple-mongo
    restart: unless-stopped
    ports:
      - '27050:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - ./mongo/users.json:/docker-entrypoint-initdb.d/users.json
      - ./mongo/events.json:/docker-entrypoint-initdb.d/events.json
      - ./mongo/init.js:/docker-entrypoint-initdb.d/init.js
  maple-auth:
    build:
      context: .
      dockerfile: apps/auth/dockerfile
    container_name: maple-auth
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      NODE_ENV: prod
      SERVER_PORT: 5562
      JWT_SECRET: honeyjam
      JWT_EXPIRES_IN: 1h
      JWT_REFRESH_EXPIRES_IN: 7d
      MONGO_URI: mongodb://admin:admin123@mongo:27017/?authSource=admin
      MONGO_DB_NAME: maple

  maple-gateway:
    build:
      context: .
      dockerfile: apps/gateway/dockerfile
    container_name: maple-gateway
    restart: unless-stopped
    ports:
      - '5561:5561'
    depends_on:
      - mongo
    environment:
      NODE_ENV: prod
      SERVER_PORT: 5561
      JWT_SECRET: honeyjam
      JWT_EXPIRES_IN: 1h
      AUTH_SERVER_URL: http://maple-auth:5562
      EVENT_SERVER_URL: http://maple-event:5563

  maple-event:
    build:
      context: .
      dockerfile: apps/event/dockerfile
    container_name: maple-event
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      NODE_ENV: prod
      SERVER_PORT: 5563
      JWT_SECRET: honeyjam
      JWT_EXPIRES_IN: 1h
      MONGO_URI: mongodb://admin:admin123@mongo:27017/?authSource=admin
      MONGO_DB_NAME: maple
