FROM node:18-alpine AS builder

WORKDIR /app

RUN apk add --no-cache python3 make g++ git
RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml ./
COPY nest-cli.json tsconfig*.json ./
COPY apps/auth ./apps/auth
COPY libs ./libs

RUN pnpm install
RUN pnpm build auth

# 실행 스테이지
FROM node:18-alpine AS runner

WORKDIR /app

RUN apk add --no-cache libc6-compat
RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml ./
COPY dist/apps/auth ./dist/apps/auth

RUN pnpm install --prod

CMD ["node", "dist/apps/auth/main.js"]