# 빌드 스테이지
FROM node:18-alpine AS builder

WORKDIR /app

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml ./
COPY nest-cli.json tsconfig*.json ./
COPY apps/gateway ./apps/gateway

RUN pnpm install
RUN pnpm build gateway

# 실행 스테이지
FROM node:18-alpine AS runner

WORKDIR /app
RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml ./
COPY --from=builder /app/dist/apps/gateway ./dist/apps/gateway

RUN pnpm install --prod

CMD ["node", "dist/apps/gateway/main.js"]